### ISSUE TITLE
Not able to run TemplateRandomwalk

### ISSUE THREAD

**Issue by tushar-semwal** [nekonaute/roborobo3#4]
I followed the steps to run the TemplateRandomwalk. The steps which I followed are:
1. ./makefile-manager -a TemplateRandomwalk
2. make clean
3. make
4. /roborobo -l config/template_randomwalk.properties

After this, the program crashed and threw this error:
```
Randomizing parameters
=-= Robot #0 : STARTING monitoring sensory information at iteration #0.
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted (core dumped)
```
My system's configuration is:
Core i5, 4 GB RAM 
OS: Ubuntu: 16.04 (I also tried on Ubuntu 17.10)

All other Templates are working. The issue is with the TemplateRandomwalk.

**Comment by nekonaute** [comment]
Hi Tushar,

Sorry for long delay -- I'll take a look at it. Thanks for contacting us.

I'll come back to you quickly.

Nicolas

2017-11-03 10:07 GMT+01:00 Tushar Semwal <notifications@github.com>:

**Comment by nekonaute** [comment]
Hi again,

Ok, this was a very minor but critical bug. The github is now up-to-date.

If you just want to correct the bug (e.g. you've forked your own version of
roborobo), edit TemplateRandomwalkController.h and modify the following
definition accordingly: *std::string inspect( std::string prefix = "" );*
ie. "" instead of 0

Thank you!

Cheers

Nicolas



2017-11-30 15:58 GMT+01:00 Nicolas Bredeche <nicolas.bredeche@upmc.fr>:
